# Generated by Django 5.0 on 2024-01-27 13:38

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=256)),
                ("code", models.CharField(max_length=3)),
                ("description", models.CharField(max_length=4096)),
                ("flag", models.CharField(max_length=1024)),
            ],
            options={
                "db_table": "country",
            },
        ),
        migrations.CreateModel(
            name="HotelOwner",
            fields=[
                (
                    "id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("firstname", models.CharField(max_length=128)),
                ("lastname", models.CharField(max_length=128)),
                ("business_address", models.CharField(max_length=256)),
                ("personal_tel", models.CharField(max_length=10)),
                ("business_tel", models.CharField(max_length=10)),
                ("business_email", models.CharField(max_length=128)),
                ("business_reg_no", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "hotel_owner",
            },
        ),
        migrations.CreateModel(
            name="Traveller",
            fields=[
                (
                    "id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("firstname", models.CharField(max_length=128)),
                ("lastname", models.CharField(max_length=128)),
                ("mobile", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "traveller",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.CharField(max_length=128, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=128)),
                ("latitude", models.DecimalField(decimal_places=2, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=4096)),
                ("image1", models.CharField(max_length=512)),
                ("image2", models.CharField(max_length=512)),
                ("image3", models.CharField(max_length=512)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel_hunt_api.country",
                    ),
                ),
            ],
            options={
                "db_table": "city",
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default="N/A", max_length=128)),
                ("description", models.CharField(blank=True, max_length=2048)),
                ("wifi", models.BooleanField(default=False)),
                ("parking", models.BooleanField(default=False)),
                ("pool", models.BooleanField(default=False)),
                ("restaurant", models.BooleanField(default=False)),
                ("pub", models.BooleanField(default=False)),
                ("transport", models.BooleanField(default=False)),
                ("image1", models.CharField(default="N/A", max_length=2048)),
                ("image2", models.CharField(default="N/A", max_length=2048)),
                ("image3", models.CharField(default="N/A", max_length=2048)),
                (
                    "city",
                    models.ForeignKey(
                        default="N/A",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel_hunt_api.city",
                    ),
                ),
            ],
            options={
                "db_table": "hotel",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=128)),
                ("category", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=1024)),
                ("image1", models.CharField(max_length=2048)),
                ("image2", models.CharField(max_length=2048)),
                ("image3", models.CharField(max_length=2048)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel_hunt_api.city",
                    ),
                ),
            ],
            options={
                "db_table": "location",
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="N/A", max_length=64)),
                ("start", models.DateField(default="N/A")),
                ("end", models.DateField(default="N/A")),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        default="N/A",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trip",
            },
        ),
    ]
